name: Dev deployment
on:
  push:
    branches:
      - master

jobs:
  frontend-build:
    name: Frontend Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Anulgar CLI
        run: npm install -g @angular/cli
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: ng build
      - name: Archive Dev Artifact
        uses: actions/upload-artifact@master
        with:
          name: www
          path: www

  backend-build:
    name: Backend Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./functions
        run: npm install
      - name: Build
        working-directory: ./functions
        run: npm run build

  deploy_firestore:
    name: Deploy Firestore
    needs: frontend-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy Firestore
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: vocabify-3d855

  deploy_hosting:
    name: Deploy Hosting
    needs: frontend-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: www
          path: www
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: vocabify-3d855

  deploy_functions:
    name: Deploy Functions
    needs: backend-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./functions
        run: npm install
      - name: Deploy Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: vocabify-3d855
