name: Dev deployment
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Intall Anulgar CLI
        run: npm install -g @angular/cli
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: ng build
      - name: Archive Dev Artifact
        uses: actions/upload-artifact@master
        with:
          name: www
          path: www
  deploy_firestore:
    name: Deploy Firestore
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy Firestore
        uses: joinflux/firebase-tools@master
        with:
          args: deploy --only firestore
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: vocabify-3d855
  deploy_hosting:
    name: Deploy Hosting
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: www
          path: www
      - name: Deploy to Firebase
        uses: joinflux/firebase-tools@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: vocabify-3d855
