name: Pull Request
on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Intall Ionic CLI
        run: npm install -g @ionic/cli
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: ionic build
      - name: Archive Dev Artifact
        uses: actions/upload-artifact@master
        with:
          name: www
          path: www
