name: Pull Request
on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: ng build
      - name: Archive Dev Artifact
        uses: actions/upload-artifact@master
        with:
          name: www
          path: www

  deploy_hosting:
    if: ${{ contains(github.event.*.labels.*.name, 'preview') }}
    name: Deploy Hosting
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: www
          path: www
      - name: Deploy to Firebase
        id: deploy_firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          projectId: vocabify-3d855
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_VOCABIFY_3D855 }}"
